version: '3.7'

services:
  web:
    build: .
    ports: 
      - 80:80
      - 443:443
    volumes:
      - .:/var/www/lanueva:cached
    networks:
      - lanueva_net
  db:
    image: mysql:5.7
    ports: 
      - 3306:3306
    volumes:
      - ./database/dbdata:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel
    networks:
      - lanueva_net
  redis:
    image: redis
    networks:
      - lanueva_net
networks:
  lanueva_net: